[app]
name = "<Application-Name>"
version = "1.0"
description = "<Application Description>"
author = "Younes Rabeh"
organization = "YOUNIDEV"
domain = "younidev.com"

[logging] # Enable or disable logging persistence
persistence_logging = true

[window] # Main window configuration
width = 800
height = 500
min_width = 400
min_height = 300
title = "<Application Title>"
theme_mode = "AUTO"

[resources] # Resource directories(don't change)
base = "resources"
qss = "resources/qss"
icons = "resources/icons"
images = "resources/images"
fonts = "resources/fonts"
data = "resources/data"
temp = "resources/temp"
