[app]
name = "App Name"
version = "1.0"
description = "A Template application."
author = "Younes Rabeh"
organization = "YOUNIDEV"
domain = "younidev.com"

[logging]
persistence_logging = true

[window]
width = 800
height = 500
min_width = 400
min_height = 300
title = "Application Title"
theme_mode = "AUTO"

[resources]
base = "resources"
qss = "resources/qss"
icons = "resources/icons"
images = "resources/images"
fonts = "resources/fonts"
data = "resources/data"
temp = "resources/temp"
